import { sharedStyles, navHTML, supabaseAuthScript } from './serve.js';

export function privacyPage(env) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Privacy Policy — 8epochs</title>
  <style>${sharedStyles()}
    .legal-container {
      max-width: 680px;
      margin: 0 auto;
      padding: 48px 24px 100px;
    }
    .legal-container h1 { margin-bottom: 8px; }
    .legal-meta { font-size: 0.85rem; color: var(--text-light); margin-bottom: 40px; }
    .legal-container h2 {
      font-size: 1.1rem;
      margin-top: 36px;
      margin-bottom: 12px;
      text-transform: none;
      letter-spacing: normal;
    }
    .legal-container h3 {
      font-size: 0.95rem;
      margin-top: 20px;
      margin-bottom: 8px;
      text-transform: none;
      letter-spacing: normal;
      font-weight: 600;
    }
    .legal-container p, .legal-container li {
      font-size: 0.95rem;
      line-height: 1.7;
      color: var(--text);
      margin-bottom: 12px;
    }
    .legal-container ul { padding-left: 24px; margin-bottom: 16px; }
    .legal-container li { margin-bottom: 6px; }
    .legal-container strong { font-weight: 600; }
    .legal-table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 0.9rem; }
    .legal-table th, .legal-table td { padding: 10px 12px; border: 1px solid var(--border-light); text-align: left; }
    .legal-table th { background: var(--bg-card); font-weight: 600; font-size: 0.85rem; }
  </style>
</head>
<body>
  ${navHTML()}
  <div class="legal-container">
    <h1>Privacy Policy</h1>
    <div class="legal-meta">Version 1.0 — Effective from May 2026</div>

    <h2>1. Who We Are</h2>
    <p>This service is operated by Julian Reed, a private individual based in the United Kingdom, acting as the <strong>data controller</strong> under the UK General Data Protection Regulation (UK GDPR) and the Data Protection Act 2018.</p>
    <p>ICO registration number: <strong>[TO BE ADDED]</strong></p>
    <p>Contact: <strong>[YOUR EMAIL ADDRESS]</strong></p>

    <h2>2. What Data We Collect</h2>
    <p>We collect the following categories of personal data:</p>

    <h3>Account data</h3>
    <p>Your email address, provided when you sign up or are invited to use the service.</p>

    <h3>Intake data</h3>
    <p>Your name (or preferred name), current role and industry, career stage, and motivation for using the service — provided by you on the intake form.</p>

    <h3>Questionnaire responses</h3>
    <p>Your answers to 30 personality questionnaire items, and the scores computed from those answers.</p>

    <h3>Conversation content</h3>
    <p>The full text of your conversations with the AI during the assessment, including your messages and the AI's responses.</p>

    <h3>Derived personality data</h3>
    <p>The personality profile, values assessment, vocational interest profile, and career guidance generated by the AI based on your questionnaire responses and conversation. <strong>This data may constitute special category data (data concerning psychological characteristics) under UK GDPR Article 9.</strong></p>

    <h3>CV / career experience data (optional)</h3>
    <p>If you choose to upload your CV during Phase 2 of the assessment, we process the text content of the PDF you provide. Our system automatically removes detectable personal contact information (email addresses, phone numbers, postal addresses, postcodes, and URLs) before storage. Only the substance of your career — roles, responsibilities, tenure, industries, education, and qualifications — is retained. We do not store the original PDF file. CV upload is entirely optional; the assessment works without it.</p>

    <h3>Technical data</h3>
    <p>IP address, browser type, and timestamps of your interactions with the service. This is collected automatically for security and service operation.</p>

    <h2>3. How We Use Your Data</h2>

    <table class="legal-table">
      <tr>
        <th>Purpose</th>
        <th>Data used</th>
        <th>Lawful basis (Art. 6)</th>
        <th>Special category condition (Art. 9)</th>
      </tr>
      <tr>
        <td>Providing the personality assessment</td>
        <td>Intake data, questionnaire responses, conversation content, derived personality data</td>
        <td>Explicit consent (Art. 6(1)(a))</td>
        <td>Explicit consent (Art. 9(2)(a))</td>
      </tr>
      <tr>
        <td>Account management and authentication</td>
        <td>Email address, technical data</td>
        <td>Contract (Art. 6(1)(b))</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>Security, fraud prevention, rate limiting</td>
        <td>IP address, technical data</td>
        <td>Legitimate interests (Art. 6(1)(f))</td>
        <td>N/A</td>
      </tr>
      <tr>
        <td>Legal compliance and defending legal claims</td>
        <td>Consent records, account records, transaction records</td>
        <td>Legal obligation (Art. 6(1)(c)) / Legitimate interests (Art. 6(1)(f))</td>
        <td>N/A</td>
      </tr>
    </table>

    <h2>4. AI Processing</h2>
    <p>This service uses Claude, an AI language model developed by <strong>Anthropic PBC</strong> (San Francisco, California, USA), to generate your personality assessment.</p>
    <p>When you use the assessment:</p>
    <ul>
      <li>Your questionnaire scores and conversation messages are sent to Anthropic's API for processing</li>
      <li>Anthropic processes this data as a <strong>data processor</strong> acting on our instructions</li>
      <li>Anthropic <strong>does not use your data to train its AI models</strong> (API data is excluded from training by default)</li>
      <li>Anthropic retains API logs for up to 7 days for abuse prevention, after which they are deleted</li>
      <li>A data processing agreement is in place with Anthropic incorporating the UK International Data Transfer Addendum</li>
    </ul>
    <p>The AI generates outputs based on patterns in its training data and your specific inputs. Outputs may contain errors, biases, or inaccuracies. The AI does not have access to external databases about you — it only knows what you share during the assessment.</p>

    <h2>5. Automated Decision-Making</h2>
    <p>The personality scores and career recommendations generated by this service are produced by automated processing (AI). However, these outputs are <strong>for your information and self-reflection only</strong>. No decisions with legal or similarly significant effects are made about you based on these outputs.</p>
    <p>You have the right to request human review of any output by contacting us.</p>

    <h2>6. Who We Share Your Data With</h2>
    <table class="legal-table">
      <tr><th>Recipient</th><th>Purpose</th><th>Location</th><th>Safeguard</th></tr>
      <tr>
        <td>Anthropic PBC</td>
        <td>AI processing (generating assessment)</td>
        <td>United States</td>
        <td>Data Processing Agreement with UK IDTA / Standard Contractual Clauses</td>
      </tr>
      <tr>
        <td>Supabase Inc.</td>
        <td>Database hosting (storing your account and assessment data)</td>
        <td>EU/US</td>
        <td>Data Processing Agreement</td>
      </tr>
      <tr>
        <td>Cloudflare Inc.</td>
        <td>Website hosting, security, content delivery</td>
        <td>Global (nearest data centre)</td>
        <td>Data Processing Agreement; DPF certified</td>
      </tr>
    </table>
    <p>We do <strong>not</strong> sell your personal data. We do not share your data with advertisers. We do not use your data for marketing purposes.</p>

    <h2>7. International Data Transfers</h2>
    <p>Your personal data, including conversation content and derived personality data, is transferred to the United States when processed by Anthropic's API. This transfer is protected by:</p>
    <ul>
      <li>The UK International Data Transfer Addendum (IDTA) to the EU Standard Contractual Clauses, incorporated in Anthropic's Data Processing Agreement</li>
      <li>Anthropic's technical and organisational security measures</li>
    </ul>
    <p>You can request a copy of the applicable transfer safeguards by contacting us.</p>

    <h2>8. How Long We Keep Your Data</h2>
    <table class="legal-table">
      <tr><th>Data</th><th>Retention period</th></tr>
      <tr>
        <td>Assessment data (conversations, reports, questionnaire responses)</td>
        <td>Until you delete it or delete your account</td>
      </tr>
      <tr>
        <td>Account data (email, profile)</td>
        <td>Until you delete your account</td>
      </tr>
      <tr>
        <td>Consent records</td>
        <td>6 years after account closure (for legal claims defence)</td>
      </tr>
      <tr>
        <td>Audit logs (deletion records)</td>
        <td>6 years (for legal compliance)</td>
      </tr>
      <tr>
        <td>Technical/security logs</td>
        <td>30 days</td>
      </tr>
    </table>

    <h2>9. Your Rights</h2>
    <p>Under UK GDPR, you have the following rights:</p>
    <ul>
      <li><strong>Right of access</strong> — request a copy of all personal data we hold about you</li>
      <li><strong>Right to rectification</strong> — request correction of inaccurate data</li>
      <li><strong>Right to erasure</strong> — request deletion of your data (see "Deleting Your Data" below)</li>
      <li><strong>Right to restrict processing</strong> — request that we limit how we use your data</li>
      <li><strong>Right to data portability</strong> — receive your data in a portable format</li>
      <li><strong>Right to object</strong> — object to processing based on legitimate interests</li>
      <li><strong>Right to withdraw consent</strong> — withdraw your consent at any time, without affecting the lawfulness of processing carried out before withdrawal</li>
      <li><strong>Right not to be subject to solely automated decision-making</strong> — request human review of automated outputs</li>
    </ul>
    <p>To exercise any of these rights, contact us at <strong>[YOUR EMAIL ADDRESS]</strong>. We will respond within one calendar month.</p>

    <h2>10. Deleting Your Data</h2>
    <p>You can delete your assessment data or your entire account through the account settings page on your dashboard. When you request deletion:</p>
    <ul>
      <li><strong>Assessment data deletion:</strong> All conversation transcripts, questionnaire responses, computed scores, CV text (if uploaded), and generated reports are permanently deleted. Your account remains active.</li>
      <li><strong>Account deletion:</strong> All assessment data is deleted, plus your account and email are removed. Any remaining credits are forfeited.</li>
    </ul>
    <p>In both cases, we retain the following for up to 6 years after deletion, as permitted under UK GDPR Article 17(3)(e) for the establishment, exercise, or defence of legal claims: a record that deletion occurred, when it occurred, and your original consent records.</p>
    <p>We recommend downloading your reports before requesting deletion, as this action is irreversible.</p>

    <h2>11. Cookies and Similar Technologies</h2>
    <p>This service uses only <strong>strictly necessary</strong> cookies and local storage:</p>
    <ul>
      <li><strong>Authentication session</strong> — stored in your browser's localStorage to keep you logged in. This is essential for the service to function.</li>
      <li><strong>Cloudflare security cookies</strong> (e.g., __cfruid, __cf_bm) — set automatically by Cloudflare for rate limiting and bot protection. These are strictly necessary security cookies and do not track you across sites.</li>
    </ul>
    <p>We do not use analytics cookies, advertising cookies, or any form of cross-site tracking. No consent is required for strictly necessary cookies under PECR, but we disclose them here for transparency.</p>

    <h2>12. Children</h2>
    <p>This service is not intended for anyone under the age of 18. We do not knowingly collect data from children. If you believe a child has used this service, please contact us and we will delete their data.</p>

    <h2>13. Security</h2>
    <p>We implement proportionate technical and organisational measures to protect your data, including:</p>
    <ul>
      <li>Encryption in transit (HTTPS/TLS) for all data transmission</li>
      <li>Encryption at rest for stored data (provided by our database host)</li>
      <li>Row-level security ensuring users can only access their own data</li>
      <li>Access controls and authentication for all data access</li>
      <li>API key security — credentials are stored as encrypted secrets, never exposed to browsers</li>
    </ul>

    <h2>14. Changes to This Policy</h2>
    <p>We may update this privacy policy from time to time. If we make material changes, you will be asked to review and accept the updated policy before continuing to use the service. The version number and effective date at the top of this page indicate the current version.</p>

    <h2>15. Complaints</h2>
    <p>If you have concerns about how your data is handled, please contact us first at <strong>[YOUR EMAIL ADDRESS]</strong>.</p>
    <p>You also have the right to lodge a complaint with the Information Commissioner's Office (ICO):</p>
    <ul>
      <li>Website: <a href="https://ico.org.uk" target="_blank" rel="noopener">ico.org.uk</a></li>
      <li>Helpline: 0303 123 1113</li>
    </ul>

    <div style="margin-top:48px;"><a href="/career-assessment/dashboard" style="font-size:0.9rem; color:var(--text-muted);">← Back to Dashboard</a></div>
  </div>
</body>
</html>`;
}
