import { sharedStyles, navHTML, supabaseAuthScript } from './serve.js';

export function termsPage(env) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Terms and Conditions — 8epochs</title>
  <style>${sharedStyles()}
    .legal-container {
      max-width: 680px;
      margin: 0 auto;
      padding: 48px 24px 100px;
    }
    .legal-container h1 { margin-bottom: 8px; }
    .legal-meta { font-size: 0.85rem; color: var(--text-light); margin-bottom: 40px; }
    .legal-container h2 {
      font-size: 1.1rem;
      margin-top: 36px;
      margin-bottom: 12px;
      text-transform: none;
      letter-spacing: normal;
    }
    .legal-container p, .legal-container li {
      font-size: 0.95rem;
      line-height: 1.7;
      color: var(--text);
      margin-bottom: 12px;
    }
    .legal-container ul { padding-left: 24px; margin-bottom: 16px; }
    .legal-container li { margin-bottom: 6px; }
    .legal-container strong { font-weight: 600; }
  </style>
</head>
<body>
  ${navHTML()}
  <div class="legal-container">
    <h1>Terms and Conditions</h1>
    <div class="legal-meta">Version 1.0 — Effective from May 2026</div>

    <p>Please read these terms carefully before using the 8epochs Career Personality Assessment. By using this service, you agree to be bound by these terms.</p>

    <h2>1. About This Service</h2>
    <p>8epochs Career Personality Assessment is operated by Julian Reed, a private individual based in the United Kingdom. ICO registration number: [TO BE ADDED AFTER REGISTRATION].</p>
    <p>Contact: <strong>[YOUR EMAIL ADDRESS]</strong></p>

    <h2>2. What This Service Is</h2>
    <p>This is an AI-powered self-reflection and career exploration tool. It uses artificial intelligence (specifically Claude, developed by Anthropic PBC) to conduct conversational personality assessments and generate career interest profiles.</p>

    <h2>3. What This Service Is NOT</h2>
    <p><strong>This service is not professional career counselling, occupational psychology, medical diagnosis, psychological assessment, or regulated advice of any kind.</strong></p>
    <p>Outputs are generated by an AI language model and are for informational and self-reflection purposes only. They are not a substitute for professional career counselling, occupational psychology, medical, legal, or financial advice.</p>
    <p><strong>You should not make significant career, educational, financial, or personal decisions based solely on outputs from this service.</strong></p>
    <p>This service is not a validated psychometric instrument. It does not hold BPS (British Psychological Society) registration or any other professional accreditation. The personality frameworks referenced (Big Five, MBTI, Holland Code) are used as conversational structures, not as clinically administered tests.</p>

    <h2>4. AI Limitations</h2>
    <p>The assessment is produced by an AI language model. You should be aware that:</p>
    <ul>
      <li>AI outputs may contain errors, inaccuracies, biases, omissions, or out-of-date information</li>
      <li>The AI may generate plausible-sounding content that is incorrect or misleading</li>
      <li>No guarantee is given as to the accuracy, completeness, suitability, validity, or scientific reliability of any output</li>
      <li>Outputs may reflect biases present in the AI's training data</li>
      <li>The same inputs may produce different outputs on different occasions</li>
      <li>The AI does not have access to your personal history beyond what you share during the assessment</li>
    </ul>

    <h2>5. No Professional Relationship</h2>
    <p>Use of this service does not create a counsellor-client, doctor-patient, employer-candidate, psychologist-client, or any other professional or fiduciary relationship between you and the service operator.</p>

    <h2>6. Eligibility</h2>
    <p>You must be at least 18 years old to use this service. By using the service, you confirm that you are 18 or older.</p>

    <h2>7. Access and Credits</h2>
    <p>Access to this service is by invitation only. Assessment credits are granted at the sole discretion of the service operator. Credits are non-transferable and non-refundable. Unused credits will be forfeited if you delete your account.</p>

    <h2>8. Your Responsibilities</h2>
    <p>You agree to:</p>
    <ul>
      <li>Provide truthful information about yourself during the assessment</li>
      <li>Not enter sensitive personal data about third parties</li>
      <li>Not attempt to manipulate, jailbreak, or misuse the AI system</li>
      <li>Not use outputs for making decisions about other people (hiring, admissions, etc.)</li>
      <li>Verify any information or recommendations independently before acting on them</li>
      <li>Not use the service for any unlawful purpose</li>
    </ul>

    <h2>9. Data Processing</h2>
    <p>Your personal data, including conversation content and (if you choose to upload one) your CV, is processed in accordance with our <a href="/career-assessment/privacy">Privacy Policy</a>. By using this service, you acknowledge that:</p>
    <ul>
      <li>Your conversation content is sent to Anthropic PBC (based in the United States) for AI processing</li>
      <li>Your data is stored in a database hosted by Supabase</li>
      <li>Personality assessment data may constitute special category data under UK GDPR</li>
    </ul>
    <p>Separate explicit consent for data processing is obtained before your first assessment.</p>

    <h2>10. Intellectual Property</h2>
    <p>You retain rights in the content you provide during the assessment. We grant you a non-exclusive licence to view, download, and use your assessment outputs for personal purposes. Assessment outputs are not exclusive — the AI may generate similar content for other users.</p>
    <p>The service design, branding, and underlying technology remain the property of the service operator.</p>

    <h2>11. Limitation of Liability</h2>
    <p>To the maximum extent permitted by law:</p>
    <ul>
      <li>The service is provided "as is" without warranties of any kind, whether express or implied</li>
      <li>We do not accept liability for any indirect, consequential, or pure economic loss arising from your use of the service or reliance on its outputs</li>
      <li>Our total liability for any direct loss shall not exceed the amount you have paid for the service (if any)</li>
      <li>We do not accept liability for decisions you make based on AI-generated outputs</li>
    </ul>
    <p>Nothing in these terms excludes or limits our liability for: death or personal injury caused by negligence; fraud or fraudulent misrepresentation; or any other liability that cannot be excluded by law.</p>

    <h2>12. Service Availability</h2>
    <p>We do not guarantee uninterrupted access to the service. We may suspend, modify, or discontinue the service at any time without notice. Your conversation data is saved and you can resume an in-progress assessment when the service is available.</p>

    <h2>13. Account Termination</h2>
    <p>You may delete your account at any time through the account settings page. You can also request deletion of your assessment data without deleting your account. We may suspend or terminate your access if you breach these terms.</p>

    <h2>14. Changes to These Terms</h2>
    <p>We may update these terms from time to time. If we make material changes, you will be asked to review and accept the updated terms before continuing to use the service. Your continued use of the service after accepting updated terms constitutes agreement to the changes.</p>

    <h2>15. Complaints</h2>
    <p>If you have a complaint about the service, please contact us at <strong>[YOUR EMAIL ADDRESS]</strong>.</p>
    <p>If you have a complaint about how your personal data is handled, you have the right to lodge a complaint with the Information Commissioner's Office (ICO) at <a href="https://ico.org.uk" target="_blank" rel="noopener">ico.org.uk</a> or by calling 0303 123 1113.</p>

    <h2>16. Governing Law</h2>
    <p>These terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales, subject to your statutory consumer rights.</p>

    <h2>17. Severability</h2>
    <p>If any provision of these terms is found to be unenforceable, the remaining provisions shall continue in full force and effect.</p>

    <div style="margin-top:48px;"><a href="/career-assessment/dashboard" style="font-size:0.9rem; color:var(--text-muted);">← Back to Dashboard</a></div>
  </div>
</body>
</html>`;
}
