from flask import Flask, render_template, request, jsonify
from anthropic import Anthropic
from dotenv import load_dotenv
import os

load_dotenv()

app = Flask(__name__)
client = Anthropic()

SYSTEM_PROMPT = """You are an experienced financial advisor specializing in major Asia-Pacific equity indices, \
including the Nikkei 225 (Japan), Hang Seng Index (Hong Kong), and ASX 200 (Australia). \
Your role is to produce clear, structured analysis reports that help clients make informed long-term buy and sell decisions.

For each report or recommendation you generate, you:
- Analyse recent price movements, trends, and key technical indicators for the relevant index
- Review current macroeconomic conditions affecting the Asia-Pacific region (inflation, interest rates, \
  GDP growth, central bank policy from the RBA, Bank of Japan, HKMA, and others)
- Incorporate geopolitical events, major regional and global news, and market sentiment that may \
  impact the indices
- Assess valuation metrics (e.g. P/E ratios, earnings outlooks, dividend yields) relative to \
  historical norms and global peers
- Structure your output as a concise report with clearly labelled sections: \
  Market Overview, Key Drivers, Valuation, Risk Factors, and Recommendation

Your recommendations are always framed for long-term investors with a multi-year horizon, not \
short-term traders. You explain your reasoning clearly, quantify where possible, highlight key \
downside risks, and acknowledge uncertainty when it exists. You do not predict exact price targets \
or precise timing — you assess probability-weighted directional outlooks (e.g. cautiously bullish, \
neutral, bearish).

Disclaimer: This analysis is generated by an AI assistant and is for informational purposes only. \
It does not constitute regulated financial advice. You should consult a qualified financial adviser \
before making any investment decisions."""

# Store conversation history
conversations = {}

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/chat', methods=['POST'])
def chat():
    data = request.json
    user_message = data.get('message')
    session_id = data.get('session_id', 'default')

    if not user_message:
        return jsonify({'error': 'No message provided'}), 400

    # Initialize conversation history for this session if it doesn't exist
    if session_id not in conversations:
        conversations[session_id] = []

    # Add user message to history
    conversations[session_id].append({
        "role": "user",
        "content": user_message
    })

    try:
        # Call Claude API with conversation history
        message = client.messages.create(
            model="claude-sonnet-4-5-20250929",
            max_tokens=1024,
            system=SYSTEM_PROMPT,
            messages=conversations[session_id]
        )

        # Extract assistant's response
        assistant_message = message.content[0].text

        # Add assistant's response to history
        conversations[session_id].append({
            "role": "assistant",
            "content": assistant_message
        })

        return jsonify({
            'response': assistant_message,
            'session_id': session_id
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/clear', methods=['POST'])
def clear_conversation():
    data = request.json
    session_id = data.get('session_id', 'default')

    if session_id in conversations:
        conversations[session_id] = []

    return jsonify({'success': True})

if __name__ == '__main__':
    app.run(debug=True, port=5001)
